config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  resources :customers, shallow: true do
    resources :invoices  do
      resources :positions
    end
  end
  get 'invoices/:id/pdf' => 'invoices#invoice_pdf'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :invoices
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :customer
  has_many :positions
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :invoice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include LoadAndAuthorizeResource
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        puts 'sheeet'
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:company, :first_name, :second_name, :street, :zip, :hourly_rate, :country, :city)
    end
end

app/controllers/invoice_pdfs_controller.rb
class InvoicePdfsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "index",
        layout: "pdf"
      end
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  
  def index
    redirect_to customer_path(params[:customer_id])
  end

  def new
    @customer = Customer.find(params[:customer_id])
    @invoice = @customer.invoices.build
    @path = [@customer, @invoice]
  end

  def create
    @customer = Customer.find(params[:customer_id])
    @invoice = @customer.invoices.new(invoice_params)
    if @invoice.save
      redirect_to @invoice
    else
      redirect_to new_customer_invoice_path
    end
  end

  def show
    @customer = Customer.find(@invoice.customer_id)
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "invoice_pdf",
        layout: "pdf",
        margin: {top: 0, bottom: 0, left: 0, right: 0}
      end
    end
  end

  def edit
    @path = @invoice
  end

  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_generic
    puts 'lololololol'
  end

  private
    def invoice_params
      params.require(:invoice).permit(:name, :created_at, :updated_at)
    end

    def set_invoice
      @invoice = Invoice.find(params[:id])
    end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @invoice = Invoice.find(params[:invoice_id])
    puts @invoice.name
    @position = @invoice.positions.build
    @path = [@invoice, @position]
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
  
    
    @position = Position.new(position_params)

    # respond_to do |format|
    #   if @position.save
    #     format.html { redirect_to @position, notice: 'Position was successfully created.' }
    #     format.json { render :show, status: :created, location: @position }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @position.errors, status: :unprocessable_entity }
    #   end
    # end

    @invoice = Invoice.find(params[:invoice_id])
    @position = @invoice.positions.new(position_params)
    if @position.save
      redirect_to @invoice
    else
      redirect_to new_invoice_position_path
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def position_params
      params.require(:position).permit(:name, :description, :hours)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @customers = Customer.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sort_by_last_update(list)
    list.order("updated_at DESC")
  end

  def formatted_date(date)
    date&.strftime('%d.%m.%Y')
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
  def formal_customer(customer)
    puts customer
    if customer.company.empty?
      customer.first_name + ' ' + customer.second_name
    else
      customer.company
    end
  end

  def showCustomerName?(customer)
    unless @customer.company.empty?
      customer_full_name =  @customer.first_name + ' ' + @customer.second_name
      content_tag :li, class: "list-group-item d-flex justify-content-between" do
        content_tag(:strong, "Name: ") + content_tag(:span, customer_full_name)
      end
    end
  end
end

app/helpers/invoice_pdfs_helper.rb
module InvoicePdfsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def invoice_total(invoice)
    invoice.positions.to_ary.reduce(0) { | sum, position | sum + position_total(position)}
  end

  def invoice_number(invoice)
    6000 + invoice.id * 3
  end

  def today
    date = Date.today
    date&.strftime('%d|%m|%Y')
  end
end

app/helpers/positions_helper.rb
module PositionsHelper
  def position_total(position)
    invoice = Invoice.find(position.invoice_id)
    customer = Customer.find(invoice.customer_id)
    position.hours.to_f * customer.hourly_rate.to_f
  end
end

app/helpers/select_customer_helper.rb
module SelectCustomerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for @customer do |f| %>
    <%= f.input :company, label: 'Firma' %>
    <%= f.input :first_name, label: 'Vorname' %>
    <%= f.input :second_name, label: 'Nachname' %>
    <%= f.input :street, label: 'Straße' %>
    <%= f.input :zip, label: 'Postleitzahl' %>
    <%= f.input :city, label: 'Ort' %>
    <%= f.input :hourly_rate, label: 'Stundensatz', 
    collection: ['40', '50'], default: '40' %>
    <%= f.input :country, collection: ['Deutschland', 'Österreich'], default: 'Deutschland' %>
    <%= f.button :submit %>
  <% end %>

app/views/customers/edit.html.erb
<div class="padding">
<h1>Editing Customer</h1>
<%= render 'form', customer: @customer %>
</div>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kunden</h1>
<div class='card shadow'>
<table class="table table-hover">

  <thead>
    <tr class="cus-table-header">
      <th scope="col">Kunde</th>
      <th scope="col">Zuletzt bearbeitet</th>
    </tr>
  </thead>

  <tbody>
    <% sort_by_last_update(@customers).each do |customer| %>
      <tr scope="row" class="clickable">
        <td class="clickable-customer" id=<%= customer.id %> data-href=<%= customer_path(customer) %> ><%= formal_customer(customer) %></td>
        <td class="clickable-customer" id=<%= customer.id %> data-href=<%= customer_path(customer) %> ><%= customer.updated_at.strftime('%d.%m.%Y') %></td>
      </tr>
    <% end %> 
    <tr>
      <td colspan="2">
        <%= link_to 'New Customer', new_customer_path %>
      </td>
    </tr>
  </tbody>
</table>
<br>
</div>

app/views/customers/new.html.erb
<h1>New Customer</h1>
<%= render 'form', customer: @customer %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="cus-content-container row">
  <div class="card shadow col-sm-4 mr-auto cus-card">
    <div class="card-header">
      <strong><%= formal_customer(@customer) %></strong>
    </div>
    <ul class="list-group list-group-flush">
      <%= showCustomerName?(@customer) %>
      <li class="list-group-item d-flex justify-content-between">
        <strong>Straße:</strong> <%= @customer.street%>
      </li>
      <li class="list-group-item d-flex justify-content-between">
        <strong>Postleitzahl:</strong> <%= @customer.zip%>
      </li>
      <li class="list-group-item d-flex justify-content-between">
        <strong>Ort:</strong> <%= @customer.city%>
      </li>
      <li class="list-group-item d-flex justify-content-between">
        <strong>Land:</strong> <%= @customer.country%>
      </li>
    </ul>
    <div class="card-body clickable" id="edit-customer" data-href=<%= edit_customer_path %>>
      <!-- <%= link_to "Bearbeiten", edit_customer_path(@customer), {:class => "text-primary"} %> -->
    </div>
  </div>

  <div class="card shadow cus-card col-sm-7 ml-auto">
    <div class="card-header">
      <strong>Rechnungen</strong>
    </div>
    <table class="table">
      <thead>
        <tr class="cus-table-header">
          <th>
            Projektname
          </th>
          <th>
            Zuletzt bearbeitet
          </th>
          <th>
            Total
          </th>
          <th>
            Status
          </th>
        </tr>
      </thead>
      <tbody>
        <% @customer.invoices.each do |invoice| %>
          <tr class="clickable text-primary">
            <td class="clickable-invoice" id=<%= invoice.id %> data-href=<%= invoice_path %> ><%= invoice.name %></td>
            <td class="clickable-invoice" id=<%= invoice.id %> data-href=<%= invoice_path %> ><%= formatted_date(invoice.updated_at) %></td>
            <td class="clickable-invoice" id=<%= invoice.id %> data-href=<%= invoice_path %> ><%= invoice_total(invoice) %></td>
            <td class="clickable-invoice" id=<%= invoice.id %> data-href=<%= invoice_path %> >bezahlt</td>
          </tr>
        <% end %>
        <tr>
          <td colspan="3" class="clickable text-primary" id="new-invoice" data-href=<%= new_customer_invoice_path(@customer) %>> Neue Rechnung erstellen</td>
        </tr>
      </tbody>
    </table>
  </div>
  </div>
  
  

app/views/invoice_pdfs/index.html.erb
<p>hihihihihihihihihihihihi</p>

app/views/invoice_pdfs/index.pdf.erb
<p>hohohohohoho</p>

app/views/invoices/_form.html.erb
<%= simple_form_for(@path) do |f| %>
  <%= f.input :name, label: 'Projektname' %>
  <%= f.button :submit %>
<% end %>

app/views/invoices/edit.html.erb
<h1>Edit Invoice</h1>

<%= render 'form', invoice: @invoice %>

app/views/invoices/new.html.erb
<h1>New Customer</h1>
<%= render 'form', invoice: @invoice %>

app/views/invoices/new_generic.erb
<h1>New Generic</h1>

app/views/invoices/show.html.erb
<div class="cus-content-container">
  <div class="card shadow cus-card">
    <div class="card-header">
      <div class = "invoice-meta">
        <table>
          <tr>
            <td class="invoice-meta-tag font-weight-bold">Rechnung:</td>
            <td class="font-weight-bold"><%= @invoice.name %></td>
          </tr>
          <tr>
            <td class="invoice-meta-tag">Erstellt:</td>
            <td><%= formatted_date(@invoice.created_at) %></td>
          </tr>
          <tr>
            <td class="invoice-meta-tag">Zuletzt Bearbeitet:</td>
            <td><%= formatted_date(@invoice.updated_at) %></td>
          </tr>
          <tr>
            <td class="invoice-meta-tag">Kunde:</td>
            <td><%= link_to formal_customer(@customer), customer_path(@invoice.customer) %></td>
          </tr>
        </table>
      </div>
    </div>
    <table class="table">
      <thead>
        <tr class="cus-table-header">
          <th>
            Position
          </th>
          <th>
            Beschreibung
          </th>
          <th>
            Stunden
          </th>
          <th>
            Preis
          </th>
        </tr>
      </thead>
      <tbody>
        <% @invoice.positions.each do |position| %>
          <tr class="clickable">
            <td class="clickable-position" id=<%= position.id %> data-href=<%= position_path %> ><%= position.name %></td>
            <td class="clickable-position" id=<%= position.id %> data-href=<%= position_path %> ><%= position.description %></td>
            <td class="clickable-position" id=<%= position.id %> data-href=<%= position_path %> ><%= position.hours %></td>
            <td class="clickable-position" id=<%= position.id %> data-href=<%= position_path %> ><%= position_total(position) %></td>
          </tr>
        <% end %>
        <tr>
          <td colspan="4"><%= link_to 'Neue Position', new_invoice_position_path(@invoice) %></td>
        </tr>
        <tr>
          <td colspan="2"></td>
          <td class="font-weight-bold">Total:</td>
          <td><%= invoice_total(@invoice) %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/invoices/show.pdf.erb
<div class="pdf-content">
  <div class="pdf-logo-container ">
    <%= image_tag wicked_pdf_asset_base64('logo.jpg') %>
  </div>

  <div class="pdf-own-address">
    <h1 class="pdf-own-name light"> 
      <span>L E N A</span>
      &nbsp;
      <span>R I E G E R</span>
    </h1>
    <p>
      <span class="lol">Konstantin-Lange Str. 64</span>
      <span class="middot">&#183;</span>
      <span>12103 Berlin</span>
    </p>
    <p>wurst@wurstikowski.design</p>
    <p>+49 176 1234 5678</p>
    <p></p>
    <p></p>
  </div>

  <div class="pdf-customer-address light">
    <p class="pdf-customer-address-line"><%= formal_customer(@customer)%></p>
    <p class="pdf-customer-address-line"><%= @customer.street%></p>
    <p class="pdf-customer-address-line"><%= @customer.zip%> <%= @customer.city%></p>
    <p class="pdf-customer-address-line"><%= @customer.country %></p>
  </div>

  <div class="pdf-top-right-info light"> 
      <p class="pdf-invoice-date">Rechnungssnummer <%= invoice_number(@invoice) %></p>
      <p class="pdf-invoice-date"><%= today %></p>
  </div>

  <div class="folding-mark"></div>

  <div class="pdf-table-container">
    <h1 class="pdf-invoice-title bold"><%= @invoice.name %></h1>
    <table class="pdf-table">
      <thead>
        <tr class="bold">
          <th class="bold">Projekt</th>
          <th class="thick-horiz-borders">Leistung</th>
          <th>Stunden</th>
          <th>Preis</th>
        </tr>
      </thead>
      <tbody>
        <% @invoice.positions.each do |position| %>
          <tr class="light">
            <td><%= position.name %></td>
            <td class="thick-horiz-borders"><%= position.description %></td>
            <td class="hours-tag"><%= number_with_precision(position.hours, precision: 1, strip_insignificant_zeros: true) %></td>
            <td class="price-tag"><%= number_with_precision(position_total(position), precision: 2)%> €</td>
          </tr>
        <% end %>
          <tr>
            <td class="bold">Gesamt</td>
            <td class="thick-horiz-borders"></td>
            <td class="bold hours-tag">12</td>
            <td class="price-tag bold"><%= number_with_precision(invoice_total(@invoice), precision: 2) %> €</td>
          </tr>
      </tbody>
    </table>
    <div class="pdf-footer">
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<!-- <header class="navbar navbar-fixed-top navbar-inverse bg-primary">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo", class: "text-light" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", '#', class: "text-light" %></li>
        <li><%= link_to "Help", '#', class: "text-light" %></li>
        <li><%= link_to "Log in", '#', class: "text-light" %></li>
      </ul>
    </nav>
  </div>
</header> -->

<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">Cash Mashine</a>
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Kundenübersicht', customers_path %>
        <!-- <a class="nav-link" href="#">Kundenübersicht <span class="sr-only">(current)</span></a> -->
      </li>
      <!-- <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li> -->
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CashMachine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="main-view">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload='number_pages'>
    <div id="header">
      <%= wicked_pdf_image_tag 'mysite.jpg' %>
    </div>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/pdf.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
    <%= wicked_pdf_stylesheet_link_tag "pdf" %>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body onload='number_pages'>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/positions/_form.html.erb
<%= simple_form_for(@path) do |f| %>
  <%= f.input :name, label: 'Projekt' %>
  <%= f.input :description, label: 'Beschreibung' %>
  <%= f.input :hours, label: 'Stunden' %>
  <%= f.button :submit %>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form', position: @position %>

<%= link_to 'Show', @position %> |
<%= link_to 'Back', positions_path %>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Positions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Position', new_position_path %>

app/views/positions/new.html.erb
<h1>New Position</h1>

<%= render 'form', position: @position %>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_position_path(@position) %> |

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<div class="cus-content-container row">
  <div class="card shadow cus-card col-sm-4 mr-auto">
  <div class=" shadow cus-card">
    <div class="card-header">
      <strong>Zuletzt bearbeitete Rechnungen</strong>
    </div>
    <table class="table">
      <thead>
        <tr class="cus-table-header">
          <th>
            Rechnung
          </th>
          <th>
            Status
          </th>
          <th>
            Zuletzt bearbeitet
          </th>
          <th>
            Status
          </th>
        </tr>
      </thead>
            <tbody>
        <% @customers.each do |customer| %>
          <tr class="clickable">
            <td class="" id=<%= customer.id %>><%= formal_customer(customer) %></td>
            <td class="" id=<%= customer.id %> bla</td>
            <td class="" id=<%= customer.id %> blub</td>
            <td class="" id=<%= customer.id %> bezahlt</td>
          </tr>
        <% end %>
        <tr>
        </tr>
      </tbody>
    </table>
    </div>
  </div>